% TESTS_NOISE
%
% WACOWC2018 paper
%
%   testWACOWCmulti                   - testWACOWCmulti Simulation of VLP "naive" algorithm in a room.
%   WACOWCmulti1                      - Parameter set #1 for testWACOWCmulti
%   WACOWCmulti2                      - Parameter set #2 for testWACOWCmulti
%   WACOWCmulti3                      - Parameter set #3 for testWACOWCmulti
%   WACOWCmulti4                      - Parameter set #4 for testWACOWCmulti
%   createfigureWACOWCpos             - Formats graphs for WACOWC 2018 paper
%   computeExpPrctile                 - Computes the percentile values from an experiment data
%   plotExpGraphSE1                   - Plots rms positioning error as a function of N_p and Psi from data generated by testWACOWCmulti
%   makeSurfPlots                     - Creates surface plots from the files with basename.
%   plotErrSurface                    - Creates surface plots from one single experiment
%
%   testWACOWC                        - Run simulation with a single emitter to get reading accuracy data
%   WACOWC1                           - General conditions:
%   WACOWC2                           - General conditions:
%   WACOWC3                           - General conditions:
%   WACOWC4                           - General conditions:
%   WACOWC5                           - General conditions:
%   plotExpGraphSE                    - (testWACOW) Plots the graphs with overall data
%
%
%   test_single_em                    - 
%   plotGraphSE                       - Plots the graphs from single emitter using data in file
%
%
%
% Plot treatment
%   arrangeGraphsThreshold            - Converts surface graphs to 2D and hide values above threshold
%
% Graphics
%   drawCircleAtH                     - Draw a circle at height H, centered in Cx,Cy with radius R
%
% Templates:
%   test_template                     - Template for a simulation test
%
%
% Miscelaneous files
%   analyze_sim_data                  - This script compiles all data into a struture in order to produce the
%   analyze_sim_data_m                - This script compiles all data into a struture in order to produce the
%   createResultFilename              - UNTITLED3 Summary of this function goes here
%   createResultFilenamed             - UNTITLED3 Summary of this function goes here
%   Demo                              - General conditions:
%   Exp00                             - Exp00
%   Exp02                             - General conditions:
%   ExperimentData_01                 - General conditions:
%   run_mult_parameters               - add the path to the projective geometry functions
%   run_mult_parameters_daugther      - RUN_MULT_PARAMETERS_DAUGHTER- run a give set of parameters, refer to
%   run_sim_for_m_psi_same_np_nm      - add the path to the projective geometry functions
%   shapeResults                      - UNTITLED Summary of this function goes here
%   test_noise_full_room              - Prepare the workspace
%   test_noise_full_room_square_lamps - Prepare the workspace
%   trilateration_group_em            - Calculate the position by trilateration base on the
%   export_data_to_coordinates        - Run this script to compute and export the data to the especific experiment file
