function createfigureWACOWCpos(X1, YMatrix1)
%CREATEFIGUREWACOWCPOS Formats graphs for WACOWC 2018 paper
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 12-Jan-2018 10:04:55

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','YMinorTick','on',...
  'YScale','log',...
  'XMinorTick','on',...
  'XScale','log',...
  'XTick',[2 4 6 8 10 12 14 16 18 20]);
%% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[3 16]);
%% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.005 0.1]);
box(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'Marker','*','Parent',axes1);
set(loglog1(1),'DisplayName','\Psi_r=1');
set(loglog1(2),'DisplayName','\Psi_r=2');
set(loglog1(3),'DisplayName','\Psi_r=3');
set(loglog1(4),'DisplayName','\Psi_r=4');
set(loglog1(5),'DisplayName','\Psi_r=5');

% Create xlabel
xlabel('# of parallels');

% Create ylabel
ylabel('rms error/m');

% Create title
title('Positioning r.m.s. error (2x2 light sources)');

% Create legend
legend(axes1,'show');

